spring:
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/travels
      username: travels-user
      password: travels-password
      hikari:
        schema: travels_data
        minimum-idle: 2
        maximum-pool-size: 20
    replica:
      url: jdbc:postgresql://localhost:5432/travels
      username: travels_ro_user
      password: travels_ro_pass
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: ReadReplicaJPAHikariCP
        schema: travels_data
        minimum-idle: 2
        maximum-pool-size: 10
        idle-timeout: 30000
        read-only: true

  jpa:
    show-sql: true
    data:
      redis:
        host: localhost
        port: 6379
        password: travels-redis-pass

  flyway:
    baseline-on-migrate: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,env,metrics

  logging:
    level:
      org.hibernate.SQL: DEBUG
      com.zaxxer.hikari: INFO
      com.zaxxer.hikari.HikariConfig: DEBUG
      com.group.ms_travels.core.aop.: DEBUG


